#!/usr/bin/env bash
# PVNaive one-line Docker installer.
#
#   PVNAIVE_DOMAIN=panel.example.com bash install.sh
#
# What it does:
#   1. verifies Docker + Docker Compose v2 are available;
#   2. generates strong secrets (bootstrap proxy account, owner password) —
#      every secret is written to ./data/.env with mode 0600 and printed once;
#   3. downloads docker-compose.yml from the pinned release tag;
#   4. starts the stack and waits for readiness;
#   5. prints the panel URL, owner login and bootstrap proxy credentials.
set -Eeuo pipefail

PVNAIVE_VERSION="${PVNAIVE_VERSION:-v1.0.0}"
PVNAIVE_INSTALL_DIR="${PVNAIVE_INSTALL_DIR:-/opt/pvnaive-docker}"
REPO_RAW="https://raw.githubusercontent.com/DashSaman/PV-NativePanel/${PVNAIVE_VERSION}"
COMPOSE_URL="${REPO_RAW}/docker/docker-compose.yml"

log() { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ ${EUID} -eq 0 ]] || fail "run as root (sudo bash install.sh)"
command -v docker >/dev/null 2>&1 || fail "Docker is not installed. Install Docker first: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required (docker compose version failed)"

DOMAIN="${PVNAIVE_DOMAIN:-}"
if [[ -z "${DOMAIN}" ]]; then
  log "no PVNAIVE_DOMAIN given — using IP-based self-signed TLS (set PVNAIVE_DOMAIN for a real certificate)"
  SERVER_IP="${PVNAIVE_SERVER_IP:-$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo localhost)}"
  DOMAIN="${SERVER_IP}"
fi

mkdir -p "${PVNAIVE_INSTALL_DIR}"
cd "${PVNAIVE_INSTALL_DIR}"
ENV_FILE="${PVNAIVE_DATA_DIR:-./data}/.env"
mkdir -p "$(dirname "${ENV_FILE}")"

rand() { openssl rand -hex 12; }
rand_pass() { openssl rand -base64 18 | tr '+/' '-_'; }

if [[ -f "${ENV_FILE}" ]]; then
  log "existing installation detected at ${ENV_FILE} — reusing existing secrets"
  set -a; source "${ENV_FILE}"; set +a
else
  log "generating secrets into ${ENV_FILE}"
  PROXY_USER="pvuser$(rand | cut -c1-6)"
  PROXY_PASSWORD="$(rand_pass)"
  OWNER_EMAIL="${PVNAIVE_OWNER_EMAIL:-admin@$(rand | cut -c1-6).local}"
  OWNER_PASSWORD="${PVNAIVE_OWNER_PASSWORD:-$(rand_pass)}"
  cat > "${ENV_FILE}" <<EOF
# Generated by install.sh at $(date -u +%FT%TZ)
PVNAIVE_VERSION=${PVNAIVE_VERSION}
PVNAIVE_DOMAIN=${DOMAIN}
PVNAIVE_NAIVE_PUBLIC_HOST=${DOMAIN}
PVNAIVE_PROXY_USER=${PROXY_USER}
PVNAIVE_PROXY_PASSWORD=${PROXY_PASSWORD}
PVNAIVE_OWNER_EMAIL=${OWNER_EMAIL}
PVNAIVE_OWNER_PASSWORD=${OWNER_PASSWORD}
PVNAIVE_DATA_DIR=${PVNAIVE_DATA_DIR:-./data}
EOF
  chmod 0600 "${ENV_FILE}"
  set -a; source "${ENV_FILE}"; set +a
fi

log "downloading docker-compose.yml from ${COMPOSE_URL}"
curl -fsSL "${COMPOSE_URL}" -o docker-compose.yml

log "pulling/building image and starting stack"
docker compose up -d --build || docker compose up -d

log "waiting for the panel to become ready"
ready=0
for _ in $(seq 1 90); do
  if curl -kfsS "https://127.0.0.1/api/v1/health/ready" >/dev/null 2>&1 || curl -fsS "http://127.0.0.1/api/v1/health/ready" >/dev/null 2>&1; then
    ready=1; break
  fi
  sleep 2
done
[[ "${ready}" == "1" ]] || fail "panel did not become ready within 180s — check: docker compose logs pvnaive"

SCHEME="https"
curl -fsS "http://127.0.0.1/api/v1/health/ready" >/dev/null 2>&1 && SCHEME="http"

cat <<EOF

============================================================
  PVNaive is installed and running 🎉
============================================================
  Panel:        ${SCHEME}://${DOMAIN}/panel/
  API health:   ${SCHEME}://${DOMAIN}/api/v1/health/ready
  Owner email:  ${OWNER_EMAIL}
  Owner pass:   ${OWNER_PASSWORD}
  Naive proxy:  naive+https://${PROXY_USER}:${PROXY_PASSWORD}@${DOMAIN}:443
                (bootstrap account — creating a user in the panel
                 replaces it with the panel-managed credentials)
  Secrets file: ${ENV_FILE} (mode 0600)
  Logs:         cd ${PVNAIVE_INSTALL_DIR} && docker compose logs -f
============================================================
  Karing/NaiveProxy client: add the naive+https:// URI above.
  With a real DNS name set PVNAIVE_DOMAIN and reinstall to get
  a valid Let's Encrypt certificate automatically.
============================================================
EOF
