#!/usr/bin/env bash
# PVNaive one-line Docker installer.
#
#   PVNAIVE_DOMAIN=panel.example.com bash <(curl -fsSL \
#     https://raw.githubusercontent.com/DashSaman/PV-NativePanel/main/docker/install.sh)
#
# What it does:
#   1. verifies Docker + Docker Compose v2 are available;
#   2. fetches the repository (shallow clone, pinned branch) unless it is
#      already running from inside a checkout;
#   3. generates strong secrets (bootstrap proxy account, owner password) —
#      every secret is written to ./data/.env with mode 0600 and printed once;
#   4. builds the image locally and starts the stack;
#   5. waits for readiness and prints the panel URL, owner login and
#      bootstrap proxy credentials.
#
# Environment:
#   PVNAIVE_DOMAIN           DNS name of this server (falls back to server IP
#                            with self-signed TLS when omitted)
#   PVNAIVE_BRANCH           branch/tag to clone (default: main)
#   PVNAIVE_INSTALL_DIR      work dir (default: /opt/pvnaive)
#   PVNAIVE_DATA_DIR         data dir (default: ./data under the compose dir)
#   PVNAIVE_OWNER_EMAIL / PVNAIVE_OWNER_PASSWORD
#   PVNAIVE_PROXY_USER  / PVNAIVE_PROXY_PASSWORD
set -Eeuo pipefail

PVNAIVE_BRANCH="${PVNAIVE_BRANCH:-main}"
PVNAIVE_INSTALL_DIR="${PVNAIVE_INSTALL_DIR:-/opt/pvnaive}"
REPO_URL="https://github.com/DashSaman/PV-NativePanel.git"

log() { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ ${EUID} -eq 0 ]] || fail "run as root (sudo bash install.sh)"
command -v docker >/dev/null 2>&1 || fail "Docker is not installed. Install Docker first: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required (docker compose version failed)"

# ---------------------------------------------------------------- compose dir
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
if [[ -f "${SCRIPT_DIR}/docker-compose.yml" && -f "${SCRIPT_DIR}/Dockerfile" ]]; then
  COMPOSE_DIR="${SCRIPT_DIR}"
  log "running from an existing checkout: ${COMPOSE_DIR}"
else
  REPO_DIR="${PVNAIVE_INSTALL_DIR}/PV-NativePanel"
  if [[ -f "${REPO_DIR}/docker/docker-compose.yml" ]]; then
    log "reusing existing clone at ${REPO_DIR}"
  else
    log "cloning PV-NativePanel (${PVNAIVE_BRANCH}) into ${REPO_DIR}"
    mkdir -p "${PVNAIVE_INSTALL_DIR}"
    git clone --depth 1 --branch "${PVNAIVE_BRANCH}" "${REPO_URL}" "${REPO_DIR}" \
      || fail "git clone failed — install git or clone the repository manually"
  fi
  COMPOSE_DIR="${REPO_DIR}/docker"
fi
cd "${COMPOSE_DIR}"

DOMAIN="${PVNAIVE_DOMAIN:-}"
if [[ -z "${DOMAIN}" ]]; then
  log "no PVNAIVE_DOMAIN given — using IP-based self-signed TLS (set PVNAIVE_DOMAIN for a real certificate)"
  SERVER_IP="${PVNAIVE_SERVER_IP:-$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo localhost)}"
  DOMAIN="${SERVER_IP}"
fi

mkdir -p "${PVNAIVE_DATA_DIR:-./data}"
ENV_FILE="${PVNAIVE_DATA_DIR:-./data}/.env"
mkdir -p "$(dirname "${ENV_FILE}")"

rand() { openssl rand -hex 12; }
rand_pass() { openssl rand -base64 18 | tr '+/' '-_'; }

if [[ -f "${ENV_FILE}" ]]; then
  log "existing installation detected at ${ENV_FILE} — reusing existing secrets"
  set -a; source "${ENV_FILE}"; set +a
else
  log "generating secrets into ${ENV_FILE}"
  PROXY_USER="${PVNAIVE_PROXY_USER:-pvuser$(rand | cut -c1-6)}"
  PROXY_PASSWORD="${PVNAIVE_PROXY_PASSWORD:-$(rand_pass)}"
  OWNER_EMAIL="${PVNAIVE_OWNER_EMAIL:-admin@$(rand | cut -c1-6).local}"
  OWNER_PASSWORD="${PVNAIVE_OWNER_PASSWORD:-$(rand_pass)}"
  cat > "${ENV_FILE}" <<EOF
# Generated by install.sh at $(date -u +%FT%TZ)
PVNAIVE_VERSION=${PVNAIVE_BRANCH}
PVNAIVE_DOMAIN=${DOMAIN}
PVNAIVE_NAIVE_PUBLIC_HOST=${DOMAIN}
PVNAIVE_PROXY_USER=${PROXY_USER}
PVNAIVE_PROXY_PASSWORD=${PROXY_PASSWORD}
PVNAIVE_OWNER_EMAIL=${OWNER_EMAIL}
PVNAIVE_OWNER_PASSWORD=${OWNER_PASSWORD}
PVNAIVE_DATA_DIR=${PVNAIVE_DATA_DIR:-./data}
EOF
  chmod 0600 "${ENV_FILE}"
  set -a; source "${ENV_FILE}"; set +a
fi

log "building image and starting stack (first build compiles Go + web, be patient)"
docker compose up -d --build

log "waiting for the panel to become ready"
ready=0
for _ in $(seq 1 120); do
  if curl -kfsS "https://127.0.0.1/api/v1/health/ready" >/dev/null 2>&1 || curl -fsS "http://127.0.0.1/api/v1/health/ready" >/dev/null 2>&1; then
    ready=1; break
  fi
  sleep 2
done
[[ "${ready}" == "1" ]] || fail "panel did not become ready within 240s — check: docker compose logs pvnaive"

SCHEME="https"
curl -fsS "http://127.0.0.1/api/v1/health/ready" >/dev/null 2>&1 && SCHEME="http"

cat <<EOF

============================================================
  PVNaive is installed and running
============================================================
  Panel:        ${SCHEME}://${DOMAIN}/panel/
  API health:   ${SCHEME}://${DOMAIN}/api/v1/health/ready
  Owner email:  ${OWNER_EMAIL}
  Owner pass:   ${OWNER_PASSWORD}
  Naive proxy:  naive+https://${PROXY_USER}:${PROXY_PASSWORD}@${DOMAIN}:443
                (bootstrap account — creating a user in the panel
                 replaces it with the panel-managed credentials)
  Secrets file: ${ENV_FILE} (mode 0600)
  Logs:         cd ${COMPOSE_DIR} && docker compose logs -f
============================================================
  Karing/NaiveProxy client: add the naive+https:// URI above,
  or open the panel, create a user and scan the dual QR.
  With a real DNS name set PVNAIVE_DOMAIN to get a valid
  Let's Encrypt certificate automatically.
============================================================
EOF
