name: Hash 0029 Temporary

on:
  pull_request:

permissions:
  contents: read

jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hash migration 0029
        run: sha256sum db/migrations/0029_cover_site.up.sql > hash-0029.txt
      - uses: actions/upload-artifact@v4
        with:
          name: hash-0029
          path: hash-0029.txt
